GET http://localhost:3000/api/authors

###
POST http://localhost:3000/api/authors
Content-Type: application/json

{
    "name":"author with key",
    "olkey":"OL45685"
}

###
DELETE http://localhost:3000/api/authors/5e4eca767f80d86dd7865ee8

###
PATCH http://localhost:3000/api/authors/5e4eca767f80d86dd7865ee8
Content-Type: application/json

{
    "name":"Willeke Rietveld"
}

###
POST http://localhost:3000/api/genres
Content-Type: application/json

{
    "name":"Non-Fiction"
}

###
GET http://localhost:3000/api/genres
